/* ===========================================================================
 * Copyright (C) 2015 CapsicoHealth Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tilda.enums;

/**
 * Keeps track of a column that has been generated by the framework and for what purpose
 * 
 * @author Laurent Hasson
 *
 */
public enum FrameworkColumnType
  {
  NONE // Normal column, i.e., user-defined directly

  , OCC_CREATED // Generated OCC columns for created.
  , OCC_LASTUPDATED // Generated OCC columns for lastUpdated.
  , OCC_DELETED // Generated OCC columns for deleted.

  , TZ // added xxxTZ column to defined DATETIME columns

  , MAPPER_NAME // Mapped name

  , MAPPER_GROUP // Mapped group

  , TS // Time series column

  , FORMULA_DT // DATETIME formula which doesn't need TZ

  , FORMULA // Formula column
  
  , PIVOT // Pivotted column

    ;

    public boolean isOCC()
      {
        return this == OCC_CREATED || this == OCC_LASTUPDATED || this == OCC_DELETED;
      }

    public boolean isManaged()
      {
        return this != NONE;
      }

    public static FrameworkColumnType parse(String Str)
      {
        for (FrameworkColumnType e : FrameworkColumnType.values())
          if (Str.equalsIgnoreCase(e.name()) == true)
            return e;
        return null;
      }

    public static boolean isOCCColumnName(String Name)
      {
        return Name.equals("created") || Name.equals("lastUpdated") || Name.equals("deleted")
        // || Name.equals("createdETL") || Name.equals("lastUpdatedETL") || Name.equals("deletedETL")
        ;
      }
  }
