description = 'Tilda BigQuery - Google BigQuery database support'

dependencies {
    api project(':tilda-core')
    
    // BigQuery JDBC driver
    implementation files('../../lib/GoogleBigQueryJDBC42.jar')
    
    // Google Cloud BigQuery client libraries
    implementation 'com.google.cloud:google-cloud-bigquery:2.34.2'
    
    // External dependencies identified by analyzer
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    implementation 'org.postgresql:postgresql:42.6.0'
    implementation 'com.google.cloud:google-cloud-bigquerystorage:3.0.1'
    implementation 'com.google.cloud:google-cloud-bigquerydatatransfer:2.34.0'
}

// Source sets for BigQuery-specific code
sourceSets {
    main {
        java {
            srcDirs = ['../../src']
            // Core BigQuery classes
            include 'tilda/db/stores/BigQuery.java'
            include 'tilda/db/processors/BigQueryType.java'
            include 'tilda/db/processors/BigQueryExporter.java'
            
            // Required dependencies
            include 'tilda/db/Connection.java'             // Database connection
            include 'tilda/enums/ColumnType.java'          // Column types
            include 'tilda/utils/TextUtil.java'            // Text utilities
            include 'tilda/utils/CollectionUtil.java'      // Collection utilities
            include 'tilda/utils/PaddingTracker.java'      // Padding utilities
            include 'tilda/utils/ParseUtil.java'           // Parse utilities
            include 'tilda/utils/DateTimeUtil.java'        // DateTime utilities
            include 'tilda/utils/SystemValues.java'        // System values
            
            // Add generation classes for BigQuery
            include 'tilda/generation/bigquery/BigQueryType.java'  // BigQuery type mapping
        }
    }
    
    test {
        java {
            srcDirs = ['../../ut']
            include '**/bigquery/**'
        }
    }
}
