/* ===========================================================================
 * Copyright (C) 2020 CapsicoHealth Inc.
 * ===========================================================================
 */

package tilda.utils.gcp;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.ByteBuffer;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.google.api.gax.paging.Page;
import com.google.cloud.WriteChannel;
import com.google.cloud.storage.Blob;
import com.google.cloud.storage.BlobId;
import com.google.cloud.storage.BlobInfo;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.StorageOptions;

import tilda.utils.DurationUtil;

public class CSHelper
  {

    protected static final Logger LOG = LogManager.getLogger(CSHelper.class.getName());

    /**
     * Given the environment variable name passed in (default is {@link tilda.utils.FileUtil#_DEFAULT_ENV_VAR_NAME}),
     * looks up the value which points to a path, and then based on the project name, lookup the file
     * "[SERVICE_ACCOUNTS_CREDENTIALS_PATH]/<dataProjectName>.xxx.key.cs.json".
     * 'xxx' can be anything (and is optional) but is generally the first few characters of the original key file. This is done
     * so different keys to the same project could be used in a team while keeping file names specific to the actual key file
     * generated by GCP.
     * 
     * @param dataProjectName
     * @return An authenticated capsico-store Storage instance
     * @throws FileNotFoundException
     * @throws IOException
     */
    public static Storage getStorage(String dataProjectName)
    throws FileNotFoundException, IOException
      {
        long nanoTime = System.nanoTime();
        Storage s =  StorageOptions.newBuilder().setCredentials(AuthHelper.getCredentials(dataProjectName, "cs")).setProjectId(dataProjectName).build().getService();
        LOG.debug("Time to get a GCS storage object: "+DurationUtil.printDurationMilliSeconds(System.nanoTime()-nanoTime));
        return s;
      }

    public static Storage getStorage(String envVariable, String dataProjectName)
    throws FileNotFoundException, IOException
      {
        return StorageOptions.newBuilder().setCredentials(AuthHelper.getCredentials(envVariable, dataProjectName, "cs")).setProjectId(dataProjectName).build().getService();
      }

    public static List<String> getSubDirectories(Storage cs, String bucketName, String dir)
      {
        List<String> directories = new ArrayList<String>();
        Page<Blob> blobs = cs.list(bucketName, Storage.BlobListOption.prefix(dir), Storage.BlobListOption.currentDirectory());

        // LOG.debug("Printing remote folder names in " + dir);
        for (Blob blob : blobs.iterateAll())
          {
            if (blob.getName().endsWith("/"))
              {
                String[] parts = blob.getName().split("/");
                String folderName = parts[parts.length - 1];

                // LOG.debug(folderName);
                directories.add(folderName);
              }
          }
        return directories;
      }

    public static List<String> getObjectsinRemoteFolder(Storage cs, String bucketName, String dir)
      {
        List<String> blobObjects = new ArrayList<String>();
        Page<Blob> blobs = cs.list(bucketName, Storage.BlobListOption.prefix(dir), Storage.BlobListOption.currentDirectory());

        // LOG.debug("Printing remote objects in directory: " + dir);
        for (Blob blob : blobs.iterateAll())
          {
            if (!blob.getName().endsWith("/"))
              {
                // LOG.debug(blob.getName());
                blobObjects.add(blob.getName());
              }
          }
        return blobObjects;
      }

    public static long getRemoteFolderSize(Storage cs, String bucketName, List<String> allObjects)
    throws IOException
      {
        long length = 0;
        for (String objectName : allObjects)
          {
            Blob blob = cs.get(BlobId.of(bucketName, objectName));
            length += blob.getSize();
          }
        return length;
      }

    public static void downloadBlobsToLocalStorage(Storage cs, String bucketName, List<String> allBlobs, String localDestPath, boolean override)
    throws IOException
      {
        for (String objectName : allBlobs)
          {
            String[] parts = objectName.split("/");
            String fileName = parts[parts.length - 1];
            Path path = Paths.get(localDestPath + fileName);

            if (Files.exists(path) == false || override == true)
              {
                LOG.debug("Downloading " + objectName + " to local file system...");
                byte[] content = cs.readAllBytes(bucketName, objectName);
                Files.write(path, content);
                LOG.debug("Sucessfully downloaded " + objectName);
              }
            else
              LOG.debug("File " + objectName + " already on the local file system.");
          }
      }

    public static int upload(Storage cs, InputStream inputStream, String bucketName, String fullFileName, String mimeType)
    throws IOException
      {
        BlobInfo blobInfo = BlobInfo.newBuilder(bucketName, fullFileName).setContentType(mimeType).build();
        try (WriteChannel writer = cs.writer(blobInfo))
          {
            ReadableByteChannel channel = Channels.newChannel(inputStream);
            ByteBuffer buf = ByteBuffer.allocate(1024 * 1024 * 5);
            int totalSize = 0;
            while (channel.read(buf) != -1)
              {
                totalSize+=buf.position();
                buf.flip(); // Prepare the buffer for writing
                writer.write(buf);
                buf.clear(); // Prepare the buffer for the next read
              }
           return totalSize;
          }
      }

    /**
     * Returns the full GCS paths of direct sub-folders under {@code dir},
     * without a trailing slash.
     * E.g. for dir="reports/" the result may be ["reports/2024","reports/2025"].
     * Pass an empty string for {@code dir} to list root-level folders.
     */
    public static List<String> getSubDirectoryPaths(Storage cs, String bucketName, String dir)
      {
        List<String> paths = new ArrayList<String>();
        Page<Blob> blobs = cs.list(bucketName, Storage.BlobListOption.prefix(dir), Storage.BlobListOption.currentDirectory());
        for (Blob blob : blobs.iterateAll())
          {
            if (blob.getName().endsWith("/"))
              {
                // Skip the folder placeholder blob for the directory itself
                // (GCS returns it when a zero-byte "TCGA-Images/" object exists).
                if (blob.getName().equals(dir))
                  continue;
                String path = blob.getName();
                paths.add(path.substring(0, path.length() - 1)); // strip trailing /
              }
          }
        return paths;
      }

    /**
     * Returns all non-folder {@link Blob} objects that are direct children of
     * {@code dir} (one level deep, not recursive).
     * Pass an empty string for {@code dir} to list root-level objects.
     */
    public static List<Blob> listBlobs(Storage cs, String bucketName, String dir)
      {
        List<Blob> result = new ArrayList<Blob>();
        Page<Blob> blobs = cs.list(bucketName, Storage.BlobListOption.prefix(dir), Storage.BlobListOption.currentDirectory());
        for (Blob blob : blobs.iterateAll())
          {
            if (blob.getName().endsWith("/") == false)
              result.add(blob);
          }
        return result;
      }

    /**
     * Derives a MIME type from a GCS object path when the stored content-type
     * is absent.  Falls back to {@code application/octet-stream}.
     */
    public static String detectMimeType(String name)
      {
        if (name == null)
          return "application/octet-stream";
        String lc = name.toLowerCase();
        if (lc.endsWith(".pdf"))                          return "application/pdf";
        if (lc.endsWith(".jpg") || lc.endsWith(".jpeg")) return "image/jpeg";
        if (lc.endsWith(".png"))                          return "image/png";
        if (lc.endsWith(".gif"))                          return "image/gif";
        if (lc.endsWith(".bmp"))                          return "image/bmp";
        if (lc.endsWith(".zip"))                          return "application/zip";
        if (lc.endsWith(".json"))                         return "application/json";
        if (lc.endsWith(".csv"))                          return "text/csv";
        if (lc.endsWith(".txt"))                          return "text/plain";
        return "application/octet-stream";
      }

    public static URL genSignedUrl(Storage cs, String bucketName, String fullFileName, String mimeType)
    throws IOException
      {
        long nanoTime = System.nanoTime();
        BlobInfo blobInfo = BlobInfo.newBuilder(bucketName, fullFileName).setContentType(mimeType).build();
        URL url = cs.signUrl(blobInfo, 60, TimeUnit.MINUTES, Storage.SignUrlOption.withV4Signature());
        LOG.debug("Time to get a GCS signed link for a document: "+DurationUtil.printDurationMilliSeconds(System.nanoTime()-nanoTime));
        return url;
      }
    
  }
